name: Deploy
on: [push, workflow_dispatch]
jobs:
  lint-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint the code
        run: npm run lint
  test:
    needs: lint-dev
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run the latest image on EC2
        uses: appleboy/ssh-action@v0.1.3 # A marketplace action for SSH
        with:
          host: ${{ secrets.EC2_HOST }} # EC2 public IP stored as a secret
          username: root # Or 'ubuntu' depending on AMI
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |

            # Login to ECR on the EC2 instance (requires ECR permissions on EC2 IAM role)
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 471112967520.dkr.ecr.eu-west-1.amazonaws.com/medici_erc_prod
            
            # Pull the latest image
            docker pull 471112967520.dkr.ecr.eu-west-1.amazonaws.com/medici_erc_prod:latest
            
            # Stop and remove the old container
            docker stop medici_web_server || true
            docker rm medici_web_server || true
            
            # Run a new container
            docker run -d --name medici_web_server -p 8080:80 471112967520.dkr.ecr.eu-west-1.amazonaws.com/medici_erc_prod:latest